services:
  app:
    build: ./build/Python
    container_name: python-mott
    ports:
      - "8080:8080"             # Necessario per collegamento esterno
    volumes:
      - ./:/home/mott/ESA_Interferometric_Mission
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE 1
      - NVIDIA_VISIBLE_DEVICES=all
    command: tail -f /dev/null  # Mantieni il container in esecuzione
    stdin_open: true            # Abilita l'interazione con il terminale del container
    tty: true                   # Abilita il terminale per il container
#    GPU se necessaria
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            device_ids: ['0']
#            capabilities: [gpu]
